# Trigger the workflow on push or pull request
on:
  push:
    paths:
      - '**.php'
      - 'psalm.xml'

jobs:
  test:
    runs-on: ubuntu-latest
    name: Static analysis
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
          coverage: none

      - name: Cache composer dependencies
          uses: actions/cache@v1
          with:
            path: vendor
            key: composer-${{ hashFiles('composer.lock') }}

      - name: Install dependencies
        run: composer install -n --prefer-dist --no-suggest

      - name: Run psalm
        run: ./vendor/bin/psalm -c psalm.xml
