# Trigger the workflow on push or pull request
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Running tests
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.composer/cache/files
          key: composer-${{ hashFiles('composer.json') }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v1
        with:
          php-version: 7.4
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
          coverage: none

      - name: Install dependencies
        run: composer update --prefer-lowest --prefer-dist --no-interaction --no-suggest

      - name: Testsuite
        run: vendor/bin/phpunit
